
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/libavformat/avformat.h:7622</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class AVFormatParameters extends Structure {
	/** C type : AVRational */
	public AVRational time_base;
	public int sample_rate;
	public int channels;
	public int width;
	public int height;
	/**
	 * @see com.acuitus.wrapffmpeg.AvutilLibrary#PixelFormat<br>
	 * C type : PixelFormat
	 */
	public int pix_fmt;
	/** < Used to select DV channel. */
	public int channel;
	/**
	 * < deprecated, use demuxer-specific options instead.<br>
	 * C type : const char*
	 */
	public Pointer standard;
	/** Conversion Error : mpeg2ts_raw:1 (This runtime does not support bit fields : JNA (please use BridJ instead)) */
	/** Conversion Error : mpeg2ts_compute_pcr:1 (This runtime does not support bit fields : JNA (please use BridJ instead)) */
	/** Conversion Error : initial_pause:1 (This runtime does not support bit fields : JNA (please use BridJ instead)) */
	/** Conversion Error : prealloced_context:1 (This runtime does not support bit fields : JNA (please use BridJ instead)) */
	public AVFormatParameters() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("time_base", "sample_rate", "channels", "width", "height", "pix_fmt", "channel", "standard");
	}
	/**
	 * @param time_base C type : AVRational<br>
	 * @param pix_fmt @see com.acuitus.wrapffmpeg.AvutilLibrary#PixelFormat<br>
	 * C type : PixelFormat<br>
	 * @param channel < Used to select DV channel.<br>
	 * @param standard < deprecated, use demuxer-specific options instead.<br>
	 * C type : const char*
	 */
	public AVFormatParameters(AVRational time_base, int sample_rate, int channels, int width, int height, int pix_fmt, int channel, Pointer standard) {
		super();
		this.time_base = time_base;
		this.sample_rate = sample_rate;
		this.channels = channels;
		this.width = width;
		this.height = height;
		this.pix_fmt = pix_fmt;
		this.channel = channel;
		this.standard = standard;
	}
	public static abstract class ByReference extends AVFormatParameters implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends AVFormatParameters implements Structure.ByValue {
		
	};
}
