
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/libavformat/avformat.h:7685</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVOutputFormat extends Structure {
	/** C type : const char* */
	public String name;
	/**
	 * Descriptive name for the format, meant to be more human-readable<br>
	 * than name. You should use the NULL_IF_CONFIG_SMALL() macro<br>
	 * to define it.<br>
	 * C type : const char*
	 */
	public String long_name;
	/** C type : const char* */
	public Pointer mime_type;
	/**
	 * < comma-separated filename extensions<br>
	 * C type : const char*
	 */
	public Pointer extensions;
	/** size of private data so that it can be allocated in the wrapper */
	public int priv_data_size;
	/**
	 * output support<br>
	 * @see com.acuitus.wrapffmpeg.AvcodecLibrary#CodecID<br>
	 * < default audio codec<br>
	 * C type : CodecID
	 */
	public int audio_codec;
	/**
	 * @see com.acuitus.wrapffmpeg.AvcodecLibrary#CodecID<br>
	 * < default video codec<br>
	 * C type : CodecID
	 */
	public int video_codec;
	/** C type : write_header_callback* */
	public AVOutputFormat.write_header_callback write_header;
	/** C type : write_packet_callback* */
	public AVOutputFormat.write_packet_callback write_packet;
	/** C type : write_trailer_callback* */
	public AVOutputFormat.write_trailer_callback write_trailer;
	/**
	 * can use flags: AVFMT_NOFILE, AVFMT_NEEDNUMBER, AVFMT_RAWPICTURE,<br>
	 * AVFMT_GLOBALHEADER, AVFMT_NOTIMESTAMPS, AVFMT_VARIABLE_FPS,<br>
	 * AVFMT_NODIMENSIONS, AVFMT_NOSTREAMS
	 */
	public int flags;
	/**
	 * Currently only used to set pixel format if not YUV420P.<br>
	 * C type : set_parameters_callback*
	 */
	public AVOutputFormat.set_parameters_callback set_parameters;
	/** C type : interleave_packet_callback* */
	public AVOutputFormat.interleave_packet_callback interleave_packet;
	/**
	 * List of supported codec_id-codec_tag pairs, ordered by "better<br>
	 * choice first". The arrays are all terminated by CODEC_ID_NONE.<br>
	 * C type : AVCodecTag**
	 */
	public PointerByReference codec_tag;
	/**
	 * @see com.acuitus.wrapffmpeg.AvcodecLibrary#CodecID<br>
	 * < default subtitle codec<br>
	 * C type : CodecID
	 */
	public int subtitle_codec;
	/** C type : const AVMetadataConv* */
	public PointerByReference metadata_conv;
	/**
	 * < AVClass for the private context<br>
	 * C type : const AVClass*
	 */
	public AVClass.ByReference priv_class;
	/**
	 * Test if the given codec can be stored in this container.<br>
	 * * @return 1 if the codec is supported, 0 if it is not.<br>
	 *         A negative number if unknown.<br>
	 * C type : query_codec_callback*
	 */
	public AVOutputFormat.query_codec_callback query_codec;
	/**
	 * private fields<br>
	 * C type : AVOutputFormat*
	 */
	public AVOutputFormat.ByReference next;
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7675</i> */
	public interface write_header_callback extends Callback {
		int apply(AVFormatContext AVFormatContextPtr1);
	};
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7676</i> */
	public interface write_packet_callback extends Callback {
		int apply(AVFormatContext AVFormatContextPtr1, AVPacket pkt);
	};
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7677</i> */
	public interface write_trailer_callback extends Callback {
		int apply(AVFormatContext AVFormatContextPtr1);
	};
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7678</i> */
	public interface set_parameters_callback extends Callback {
		int apply(AVFormatContext AVFormatContextPtr1, AVFormatParameters AVFormatParametersPtr1);
	};
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7679</i> */
	public interface interleave_packet_callback extends Callback {
		int apply(AVFormatContext AVFormatContextPtr1, AVPacket out, AVPacket in, int flush);
	};
	/** <i>native declaration : /usr/include/libavformat/avformat.h:7684</i> */
	public interface query_codec_callback extends Callback {
		int apply(int id, int std_compliance);
	};
	public AVOutputFormat() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "long_name", "mime_type", "extensions", "priv_data_size", "audio_codec", "video_codec", "write_header", "write_packet", "write_trailer", "flags", "set_parameters", "interleave_packet", "codec_tag", "subtitle_codec", "metadata_conv", "priv_class", "query_codec", "next");
	}
	public static class ByReference extends AVOutputFormat implements Structure.ByReference {
		
	};
	public static class ByValue extends AVOutputFormat implements Structure.ByValue {
		
	};
}
