
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/libavcodec/avcodec.h:3847</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVPanScan extends Structure {
	/**
	 * id<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.
	 */
	public int id;
	/**
	 * width and height in 1/16 pel<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.
	 */
	public int width;
	public int height;
	/**
	 * position of the top left corner in 1/16 pel for up to 3 fields/frames<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.<br>
	 * C type : int16_t[3][2]
	 */
	public short[] position = new short[((3) * (2))];
	public AVPanScan() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("id", "width", "height", "position");
	}
	/**
	 * @param id id<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.<br>
	 * @param width width and height in 1/16 pel<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.<br>
	 * @param position position of the top left corner in 1/16 pel for up to 3 fields/frames<br>
	 * - encoding: Set by user.<br>
	 * - decoding: Set by libavcodec.<br>
	 * C type : int16_t[3][2]
	 */
	public AVPanScan(int id, int width, int height, short position[]) {
		super();
		this.id = id;
		this.width = width;
		this.height = height;
		if ((position.length != this.position.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.position = position;
	}
	public static class ByReference extends AVPanScan implements Structure.ByReference {
		
	};
	public static class ByValue extends AVPanScan implements Structure.ByValue {
		
	};
}
