
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/libavformat/avio.h:7059</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class URLPollEntry extends Structure {
	/** C type : URLContext* */
	public URLContext.ByReference handle;
	public int events;
	public int revents;
	public URLPollEntry() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "events", "revents");
	}
	/** @param handle C type : URLContext* */
	public URLPollEntry(URLContext.ByReference handle, int events, int revents) {
		super();
		this.handle = handle;
		this.events = events;
		this.revents = revents;
	}
	public static class ByReference extends URLPollEntry implements Structure.ByReference {
		
	};
	public static class ByValue extends URLPollEntry implements Structure.ByValue {
		
	};
}
