package wrapffmpeg;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavcodec/avcodec.h:3023</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVBitStreamFilter extends Structure {
	/** C type : const char* */
	public Pointer name;
	public int priv_data_size;
	/** C type : filter_callback* */
	public AVBitStreamFilter.filter_callback filter;
	/** C type : close_callback* */
	public AVBitStreamFilter.close_callback close;
	/** C type : AVBitStreamFilter* */
	public AVBitStreamFilter.ByReference next;
	/** <i>native declaration : libavcodec/avcodec.h:3021</i> */
	public interface filter_callback extends Callback {
		int apply(AVBitStreamFilterContext bsfc, AVCodecContext avctx, Pointer args, PointerByReference poutbuf, IntByReference poutbuf_size, Pointer buf, int buf_size, int keyframe);
	};
	/** <i>native declaration : libavcodec/avcodec.h:3022</i> */
	public interface close_callback extends Callback {
		void apply(AVBitStreamFilterContext bsfc);
	};
	public AVBitStreamFilter() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "priv_data_size", "filter", "close", "next");
	}
	/**
	 * @param name C type : const char*<br>
	 * @param filter C type : filter_callback*<br>
	 * @param close C type : close_callback*<br>
	 * @param next C type : AVBitStreamFilter*
	 */
	public AVBitStreamFilter(Pointer name, int priv_data_size, AVBitStreamFilter.filter_callback filter, AVBitStreamFilter.close_callback close, AVBitStreamFilter.ByReference next) {
		super();
		this.name = name;
		this.priv_data_size = priv_data_size;
		this.filter = filter;
		this.close = close;
		this.next = next;
	}
	public static class ByReference extends AVBitStreamFilter implements Structure.ByReference {
		
	};
	public static class ByValue extends AVBitStreamFilter implements Structure.ByValue {
		
	};
}
