package wrapffmpeg;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavutil/buffer.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVBufferRef extends Structure {
	/** C type : AVBuffer* */
	public PointerByReference buffer;
	/**
	 * The data buffer. It is considered writable if and only if<br>
	 * this is the only reference to the buffer, in which case<br>
	 * av_buffer_is_writable() returns 1.<br>
	 * C type : uint8_t*
	 */
	public Pointer data;
	/** Size of data in bytes. */
	public int size;
	public AVBufferRef() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("buffer", "data", "size");
	}
	/**
	 * @param buffer C type : AVBuffer*<br>
	 * @param data The data buffer. It is considered writable if and only if<br>
	 * this is the only reference to the buffer, in which case<br>
	 * av_buffer_is_writable() returns 1.<br>
	 * C type : uint8_t*<br>
	 * @param size Size of data in bytes.
	 */
	public AVBufferRef(PointerByReference buffer, Pointer data, int size) {
		super();
		this.buffer = buffer;
		this.data = data;
		this.size = size;
	}
	public static class ByReference extends AVBufferRef implements Structure.ByReference {
		
	};
	public static class ByValue extends AVBufferRef implements Structure.ByValue {
		
	};
}
