package wraplibvorbis;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:69</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class alloc_chain extends Structure {
	/** C type : void* */
	public Pointer ptr;
	/** C type : alloc_chain* */
	public alloc_chain.ByReference next;
	public alloc_chain() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ptr", "next");
	}
	/**
	 * @param ptr C type : void*<br>
	 * @param next C type : alloc_chain*
	 */
	public alloc_chain(Pointer ptr, alloc_chain.ByReference next) {
		super();
		this.ptr = ptr;
		this.next = next;
	}
	public static class ByReference extends alloc_chain implements Structure.ByReference {
		
	};
	public static class ByValue extends alloc_chain implements Structure.ByValue {
		
	};
}
