package wraplibvorbis;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ogg/ogg.h:56</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ogg_packet extends Structure {
	/** C type : unsigned char* */
	public Pointer packet;
	public NativeLong bytes;
	public NativeLong b_o_s;
	public NativeLong e_o_s;
	/** C type : ogg_int64_t */
	public long granulepos;
	/**
	 * sequence number for decode; the framing<br>
	 * knows where there's a hole in the data,<br>
	 * but we need coupling so that the codec<br>
	 * (which is in a separate abstraction<br>
	 * layer) also knows about the gap<br>
	 * C type : ogg_int64_t
	 */
	public long packetno;
	public ogg_packet() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("packet", "bytes", "b_o_s", "e_o_s", "granulepos", "packetno");
	}
	/**
	 * @param packet C type : unsigned char*<br>
	 * @param granulepos C type : ogg_int64_t<br>
	 * @param packetno sequence number for decode; the framing<br>
	 * knows where there's a hole in the data,<br>
	 * but we need coupling so that the codec<br>
	 * (which is in a separate abstraction<br>
	 * layer) also knows about the gap<br>
	 * C type : ogg_int64_t
	 */
	public ogg_packet(Pointer packet, NativeLong bytes, NativeLong b_o_s, NativeLong e_o_s, long granulepos, long packetno) {
		super();
		this.packet = packet;
		this.bytes = bytes;
		this.b_o_s = b_o_s;
		this.e_o_s = e_o_s;
		this.granulepos = granulepos;
		this.packetno = packetno;
	}
	public static class ByReference extends ogg_packet implements Structure.ByReference {
		
	};
	public static class ByValue extends ogg_packet implements Structure.ByValue {
		
	};
}
