package wraplibvorbis;
import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ogg/ogg.h:3</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ogg_iovec_t extends Structure {
	/** C type : void* */
	public Pointer iov_base;
	public NativeSize iov_len;
	public ogg_iovec_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("iov_base", "iov_len");
	}
	/** @param iov_base C type : void* */
	public ogg_iovec_t(Pointer iov_base, NativeSize iov_len) {
		super();
		this.iov_base = iov_base;
		this.iov_len = iov_len;
	}
	public static class ByReference extends ogg_iovec_t implements Structure.ByReference {
		
	};
	public static class ByValue extends ogg_iovec_t implements Structure.ByValue {
		
	};
}
