package wraplibvorbis;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ogg/ogg.h:16</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ogg_page extends Structure {
	/** C type : unsigned char* */
	public Pointer header;
	public NativeLong header_len;
	/** C type : unsigned char* */
	public Pointer body;
	public NativeLong body_len;
	public ogg_page() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("header", "header_len", "body", "body_len");
	}
	/**
	 * @param header C type : unsigned char*<br>
	 * @param body C type : unsigned char*
	 */
	public ogg_page(Pointer header, NativeLong header_len, Pointer body, NativeLong body_len) {
		super();
		this.header = header;
		this.header_len = header_len;
		this.body = body;
		this.body_len = body_len;
	}
	public static class ByReference extends ogg_page implements Structure.ByReference {
		
	};
	public static class ByValue extends ogg_page implements Structure.ByValue {
		
	};
}
