package wraplibvorbis;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>ogg</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface OggLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ogg";
//	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(OggLibrary.JNA_LIBRARY_NAME);
//	public static final OggLibrary INSTANCE = (OggLibrary)Native.loadLibrary(OggLibrary.JNA_LIBRARY_NAME, OggLibrary.class);
	/**
	 * Original signature : <code>void oggpack_writeinit(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:67</i>
	 */
	void oggpack_writeinit(oggpack_buffer b);
	/**
	 * Original signature : <code>int oggpack_writecheck(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:69</i>
	 */
	int oggpack_writecheck(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpack_writetrunc(oggpack_buffer*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:71</i>
	 */
	void oggpack_writetrunc(oggpack_buffer b, NativeLong bits);
	/**
	 * Original signature : <code>void oggpack_writealign(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:73</i>
	 */
	void oggpack_writealign(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpack_writecopy(oggpack_buffer*, void*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:75</i>
	 */
	void oggpack_writecopy(oggpack_buffer b, Pointer source, NativeLong bits);
	/**
	 * Original signature : <code>void oggpack_reset(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:77</i>
	 */
	void oggpack_reset(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpack_writeclear(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:79</i>
	 */
	void oggpack_writeclear(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpack_readinit(oggpack_buffer*, unsigned char*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:81</i><br>
	 * @deprecated use the safer methods {@link #oggpack_readinit(wraplibvorbis.oggpack_buffer, java.nio.ByteBuffer, int)} and {@link #oggpack_readinit(wraplibvorbis.oggpack_buffer, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	void oggpack_readinit(oggpack_buffer b, Pointer buf, int bytes);
	/**
	 * Original signature : <code>void oggpack_readinit(oggpack_buffer*, unsigned char*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:81</i>
	 */
	void oggpack_readinit(oggpack_buffer b, ByteBuffer buf, int bytes);
	/**
	 * Original signature : <code>void oggpack_write(oggpack_buffer*, unsigned long, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:83</i>
	 */
	void oggpack_write(oggpack_buffer b, NativeLong value, int bits);
	/**
	 * Original signature : <code>long oggpack_look(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:85</i>
	 */
	NativeLong oggpack_look(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>long oggpack_look1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:87</i>
	 */
	NativeLong oggpack_look1(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpack_adv(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:89</i>
	 */
	void oggpack_adv(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>void oggpack_adv1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:91</i>
	 */
	void oggpack_adv1(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpack_read(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:93</i>
	 */
	NativeLong oggpack_read(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>long oggpack_read1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:95</i>
	 */
	NativeLong oggpack_read1(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpack_bytes(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:97</i>
	 */
	NativeLong oggpack_bytes(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpack_bits(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:99</i>
	 */
	NativeLong oggpack_bits(oggpack_buffer b);
	/**
	 * Original signature : <code>char* oggpack_get_buffer(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:101</i>
	 */
	Pointer oggpack_get_buffer(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_writeinit(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:103</i>
	 */
	void oggpackB_writeinit(oggpack_buffer b);
	/**
	 * Original signature : <code>int oggpackB_writecheck(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:105</i>
	 */
	int oggpackB_writecheck(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_writetrunc(oggpack_buffer*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:107</i>
	 */
	void oggpackB_writetrunc(oggpack_buffer b, NativeLong bits);
	/**
	 * Original signature : <code>void oggpackB_writealign(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:109</i>
	 */
	void oggpackB_writealign(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_writecopy(oggpack_buffer*, void*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:111</i>
	 */
	void oggpackB_writecopy(oggpack_buffer b, Pointer source, NativeLong bits);
	/**
	 * Original signature : <code>void oggpackB_reset(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:113</i>
	 */
	void oggpackB_reset(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_writeclear(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:115</i>
	 */
	void oggpackB_writeclear(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_readinit(oggpack_buffer*, unsigned char*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:117</i><br>
	 * @deprecated use the safer methods {@link #oggpackB_readinit(wraplibvorbis.oggpack_buffer, java.nio.ByteBuffer, int)} and {@link #oggpackB_readinit(wraplibvorbis.oggpack_buffer, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	void oggpackB_readinit(oggpack_buffer b, Pointer buf, int bytes);
	/**
	 * Original signature : <code>void oggpackB_readinit(oggpack_buffer*, unsigned char*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:117</i>
	 */
	void oggpackB_readinit(oggpack_buffer b, ByteBuffer buf, int bytes);
	/**
	 * Original signature : <code>void oggpackB_write(oggpack_buffer*, unsigned long, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:119</i>
	 */
	void oggpackB_write(oggpack_buffer b, NativeLong value, int bits);
	/**
	 * Original signature : <code>long oggpackB_look(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:121</i>
	 */
	NativeLong oggpackB_look(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>long oggpackB_look1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:123</i>
	 */
	NativeLong oggpackB_look1(oggpack_buffer b);
	/**
	 * Original signature : <code>void oggpackB_adv(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:125</i>
	 */
	void oggpackB_adv(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>void oggpackB_adv1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:127</i>
	 */
	void oggpackB_adv1(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpackB_read(oggpack_buffer*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:129</i>
	 */
	NativeLong oggpackB_read(oggpack_buffer b, int bits);
	/**
	 * Original signature : <code>long oggpackB_read1(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:131</i>
	 */
	NativeLong oggpackB_read1(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpackB_bytes(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:133</i>
	 */
	NativeLong oggpackB_bytes(oggpack_buffer b);
	/**
	 * Original signature : <code>long oggpackB_bits(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:135</i>
	 */
	NativeLong oggpackB_bits(oggpack_buffer b);
	/**
	 * Original signature : <code>char* oggpackB_get_buffer(oggpack_buffer*)</code><br>
	 * <i>native declaration : ogg/ogg.h:137</i>
	 */
	Pointer oggpackB_get_buffer(oggpack_buffer b);
	/**
	 * Original signature : <code>int ogg_stream_packetin(ogg_stream_state*, ogg_packet*)</code><br>
	 * <i>native declaration : ogg/ogg.h:139</i>
	 */
	int ogg_stream_packetin(ogg_stream_state os, ogg_packet op);
	/**
	 * Original signature : <code>int ogg_stream_iovecin(ogg_stream_state*, ogg_iovec_t*, int, long, ogg_int64_t)</code><br>
	 * <i>native declaration : ogg/ogg.h:141</i>
	 */
	int ogg_stream_iovecin(ogg_stream_state os, ogg_iovec_t iov, int count, NativeLong e_o_s, long granulepos);
	/**
	 * Original signature : <code>int ogg_stream_pageout(ogg_stream_state*, ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:143</i>
	 */
	int ogg_stream_pageout(ogg_stream_state os, ogg_page og);
	/**
	 * Original signature : <code>int ogg_stream_pageout_fill(ogg_stream_state*, ogg_page*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:145</i>
	 */
	int ogg_stream_pageout_fill(ogg_stream_state os, ogg_page og, int nfill);
	/**
	 * Original signature : <code>int ogg_stream_flush(ogg_stream_state*, ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:147</i>
	 */
	int ogg_stream_flush(ogg_stream_state os, ogg_page og);
	/**
	 * Original signature : <code>int ogg_stream_flush_fill(ogg_stream_state*, ogg_page*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:149</i>
	 */
	int ogg_stream_flush_fill(ogg_stream_state os, ogg_page og, int nfill);
	/**
	 * Original signature : <code>int ogg_sync_init(ogg_sync_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:151</i>
	 */
	int ogg_sync_init(ogg_sync_state oy);
	/**
	 * Original signature : <code>int ogg_sync_clear(ogg_sync_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:153</i>
	 */
	int ogg_sync_clear(ogg_sync_state oy);
	/**
	 * Original signature : <code>int ogg_sync_reset(ogg_sync_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:155</i>
	 */
	int ogg_sync_reset(ogg_sync_state oy);
	/**
	 * Original signature : <code>int ogg_sync_destroy(ogg_sync_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:157</i>
	 */
	int ogg_sync_destroy(ogg_sync_state oy);
	/**
	 * Original signature : <code>int ogg_sync_check(ogg_sync_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:159</i>
	 */
	int ogg_sync_check(ogg_sync_state oy);
	/**
	 * Original signature : <code>char* ogg_sync_buffer(ogg_sync_state*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:161</i>
	 */
	Pointer ogg_sync_buffer(ogg_sync_state oy, NativeLong size);
	/**
	 * Original signature : <code>int ogg_sync_wrote(ogg_sync_state*, long)</code><br>
	 * <i>native declaration : ogg/ogg.h:163</i>
	 */
	int ogg_sync_wrote(ogg_sync_state oy, NativeLong bytes);
	/**
	 * Original signature : <code>long ogg_sync_pageseek(ogg_sync_state*, ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:165</i>
	 */
	NativeLong ogg_sync_pageseek(ogg_sync_state oy, ogg_page og);
	/**
	 * Original signature : <code>int ogg_sync_pageout(ogg_sync_state*, ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:167</i>
	 */
	int ogg_sync_pageout(ogg_sync_state oy, ogg_page og);
	/**
	 * Original signature : <code>int ogg_stream_pagein(ogg_stream_state*, ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:169</i>
	 */
	int ogg_stream_pagein(ogg_stream_state os, ogg_page og);
	/**
	 * Original signature : <code>int ogg_stream_packetout(ogg_stream_state*, ogg_packet*)</code><br>
	 * <i>native declaration : ogg/ogg.h:171</i>
	 */
	int ogg_stream_packetout(ogg_stream_state os, ogg_packet op);
	/**
	 * Original signature : <code>int ogg_stream_packetpeek(ogg_stream_state*, ogg_packet*)</code><br>
	 * <i>native declaration : ogg/ogg.h:173</i>
	 */
	int ogg_stream_packetpeek(ogg_stream_state os, ogg_packet op);
	/**
	 * Original signature : <code>int ogg_stream_init(ogg_stream_state*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:175</i>
	 */
	int ogg_stream_init(ogg_stream_state os, int serialno);
	/**
	 * Original signature : <code>int ogg_stream_clear(ogg_stream_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:177</i>
	 */
	int ogg_stream_clear(ogg_stream_state os);
	/**
	 * Original signature : <code>int ogg_stream_reset(ogg_stream_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:179</i>
	 */
	int ogg_stream_reset(ogg_stream_state os);
	/**
	 * Original signature : <code>int ogg_stream_reset_serialno(ogg_stream_state*, int)</code><br>
	 * <i>native declaration : ogg/ogg.h:181</i>
	 */
	int ogg_stream_reset_serialno(ogg_stream_state os, int serialno);
	/**
	 * Original signature : <code>int ogg_stream_destroy(ogg_stream_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:183</i>
	 */
	int ogg_stream_destroy(ogg_stream_state os);
	/**
	 * Original signature : <code>int ogg_stream_check(ogg_stream_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:185</i>
	 */
	int ogg_stream_check(ogg_stream_state os);
	/**
	 * Original signature : <code>int ogg_stream_eos(ogg_stream_state*)</code><br>
	 * <i>native declaration : ogg/ogg.h:187</i>
	 */
	int ogg_stream_eos(ogg_stream_state os);
	/**
	 * Original signature : <code>void ogg_page_checksum_set(ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:189</i>
	 */
	void ogg_page_checksum_set(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_version(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:191</i>
	 */
	int ogg_page_version(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_continued(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:193</i>
	 */
	int ogg_page_continued(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_bos(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:195</i>
	 */
	int ogg_page_bos(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_eos(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:197</i>
	 */
	int ogg_page_eos(ogg_page og);
	/**
	 * Original signature : <code>ogg_int64_t ogg_page_granulepos(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:199</i>
	 */
	long ogg_page_granulepos(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_serialno(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:201</i>
	 */
	int ogg_page_serialno(ogg_page og);
	/**
	 * Original signature : <code>long ogg_page_pageno(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:203</i>
	 */
	NativeLong ogg_page_pageno(ogg_page og);
	/**
	 * Original signature : <code>int ogg_page_packets(const ogg_page*)</code><br>
	 * <i>native declaration : ogg/ogg.h:205</i>
	 */
	int ogg_page_packets(ogg_page og);
	/**
	 * Original signature : <code>void ogg_packet_clear(ogg_packet*)</code><br>
	 * <i>native declaration : ogg/ogg.h:207</i>
	 */
	void ogg_packet_clear(ogg_packet op);
}
