package wraplibvorbis;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ogg/ogg.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class oggpack_buffer extends Structure {
	public NativeLong endbyte;
	public int endbit;
	/** C type : unsigned char* */
	public Pointer buffer;
	/** C type : unsigned char* */
	public Pointer ptr;
	public NativeLong storage;
	public oggpack_buffer() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("endbyte", "endbit", "buffer", "ptr", "storage");
	}
	/**
	 * @param buffer C type : unsigned char*<br>
	 * @param ptr C type : unsigned char*
	 */
	public oggpack_buffer(NativeLong endbyte, int endbit, Pointer buffer, Pointer ptr, NativeLong storage) {
		super();
		this.endbyte = endbyte;
		this.endbit = endbit;
		this.buffer = buffer;
		this.ptr = ptr;
		this.storage = storage;
	}
	public static class ByReference extends oggpack_buffer implements Structure.ByReference {
		
	};
	public static class ByValue extends oggpack_buffer implements Structure.ByValue {
		
	};
}
