package wraplibvorbis;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;
/**
 * JNA Wrapper for library <b>vorbis</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface VorbisLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "vorbis";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(VorbisLibrary.JNA_LIBRARY_NAME);
	public static final VorbisLibrary INSTANCE = (VorbisLibrary)Native.loadLibrary(VorbisLibrary.JNA_LIBRARY_NAME, VorbisLibrary.class);
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EBADLINK = (int)-137;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_ENOTVORBIS = (int)-132;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_HOLE = (int)-3;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EBADHEADER = (int)-133;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_ENOSEEK = (int)-138;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EINVAL = (int)-131;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EFAULT = (int)-129;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EREAD = (int)-128;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_ENOTAUDIO = (int)-135;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EOF = (int)-2;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EVERSION = (int)-134;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EBADPACKET = (int)-136;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_EIMPL = (int)-130;
	/** <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h</i> */
	public static final int OV_FALSE = (int)-1;
	/**
	 * Original signature : <code>void vorbis_info_init(vorbis_info*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:85</i>
	 */
	void vorbis_info_init(vorbis_info vi);
	/**
	 * Original signature : <code>void vorbis_info_clear(vorbis_info*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:87</i>
	 */
	void vorbis_info_clear(vorbis_info vi);
	/**
	 * Original signature : <code>int vorbis_info_blocksize(vorbis_info*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:89</i>
	 */
	int vorbis_info_blocksize(vorbis_info vi, int zo);
	/**
	 * Original signature : <code>void vorbis_comment_init(vorbis_comment*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:91</i>
	 */
	void vorbis_comment_init(vorbis_comment vc);
	/**
	 * Original signature : <code>void vorbis_comment_add(vorbis_comment*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:93</i><br>
	 * @deprecated use the safer methods {@link #vorbis_comment_add(wraplibvorbis.vorbis_comment, java.lang.String)} and {@link #vorbis_comment_add(wraplibvorbis.vorbis_comment, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void vorbis_comment_add(vorbis_comment vc, Pointer comment);
	/**
	 * Original signature : <code>void vorbis_comment_add(vorbis_comment*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:93</i>
	 */
	void vorbis_comment_add(vorbis_comment vc, String comment);
	/**
	 * Original signature : <code>void vorbis_comment_add_tag(vorbis_comment*, const char*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:95</i><br>
	 * @deprecated use the safer methods {@link #vorbis_comment_add_tag(wraplibvorbis.vorbis_comment, java.lang.String, java.lang.String)} and {@link #vorbis_comment_add_tag(wraplibvorbis.vorbis_comment, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void vorbis_comment_add_tag(vorbis_comment vc, Pointer tag, Pointer contents);
	/**
	 * Original signature : <code>void vorbis_comment_add_tag(vorbis_comment*, const char*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:95</i>
	 */
	void vorbis_comment_add_tag(vorbis_comment vc, String tag, String contents);
	/**
	 * Original signature : <code>char* vorbis_comment_query(vorbis_comment*, const char*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:97</i><br>
	 * @deprecated use the safer methods {@link #vorbis_comment_query(wraplibvorbis.vorbis_comment, java.lang.String, int)} and {@link #vorbis_comment_query(wraplibvorbis.vorbis_comment, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	Pointer vorbis_comment_query(vorbis_comment vc, Pointer tag, int count);
	/**
	 * Original signature : <code>char* vorbis_comment_query(vorbis_comment*, const char*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:97</i>
	 */
	Pointer vorbis_comment_query(vorbis_comment vc, String tag, int count);
	/**
	 * Original signature : <code>int vorbis_comment_query_count(vorbis_comment*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:99</i><br>
	 * @deprecated use the safer methods {@link #vorbis_comment_query_count(wraplibvorbis.vorbis_comment, java.lang.String)} and {@link #vorbis_comment_query_count(wraplibvorbis.vorbis_comment, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int vorbis_comment_query_count(vorbis_comment vc, Pointer tag);
	/**
	 * Original signature : <code>int vorbis_comment_query_count(vorbis_comment*, const char*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:99</i>
	 */
	int vorbis_comment_query_count(vorbis_comment vc, String tag);
	/**
	 * Original signature : <code>void vorbis_comment_clear(vorbis_comment*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:101</i>
	 */
	void vorbis_comment_clear(vorbis_comment vc);
	/**
	 * Original signature : <code>int vorbis_block_init(vorbis_dsp_state*, vorbis_block*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:103</i>
	 */
	int vorbis_block_init(vorbis_dsp_state v, vorbis_block vb);
	/**
	 * Original signature : <code>int vorbis_block_clear(vorbis_block*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:105</i>
	 */
	int vorbis_block_clear(vorbis_block vb);
	/**
	 * Original signature : <code>void vorbis_dsp_clear(vorbis_dsp_state*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:107</i>
	 */
	void vorbis_dsp_clear(vorbis_dsp_state v);
	/**
	 * Original signature : <code>double vorbis_granule_time(vorbis_dsp_state*, ogg_int64_t)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:109</i>
	 */
	double vorbis_granule_time(vorbis_dsp_state v, long granulepos);
	/**
	 * Original signature : <code>char* vorbis_version_string()</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:111</i>
	 */
	Pointer vorbis_version_string();
	/**
	 * Original signature : <code>int vorbis_analysis_init(vorbis_dsp_state*, vorbis_info*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:113</i>
	 */
	int vorbis_analysis_init(vorbis_dsp_state v, vorbis_info vi);
	/**
	 * Original signature : <code>int vorbis_commentheader_out(vorbis_comment*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:115</i>
	 */
	int vorbis_commentheader_out(vorbis_comment vc, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_analysis_headerout(vorbis_dsp_state*, vorbis_comment*, ogg_packet*, ogg_packet*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:117</i>
	 */
	int vorbis_analysis_headerout(vorbis_dsp_state v, vorbis_comment vc, ogg_packet op, ogg_packet op_comm, ogg_packet op_code);
	/**
	 * Original signature : <code>float** vorbis_analysis_buffer(vorbis_dsp_state*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:119</i>
	 */
	PointerByReference vorbis_analysis_buffer(vorbis_dsp_state v, int vals);
	/**
	 * Original signature : <code>int vorbis_analysis_wrote(vorbis_dsp_state*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:121</i>
	 */
	int vorbis_analysis_wrote(vorbis_dsp_state v, int vals);
	/**
	 * Original signature : <code>int vorbis_analysis_blockout(vorbis_dsp_state*, vorbis_block*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:123</i>
	 */
	int vorbis_analysis_blockout(vorbis_dsp_state v, vorbis_block vb);
	/**
	 * Original signature : <code>int vorbis_analysis(vorbis_block*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:125</i>
	 */
	int vorbis_analysis(vorbis_block vb, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_bitrate_addblock(vorbis_block*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:127</i>
	 */
	int vorbis_bitrate_addblock(vorbis_block vb);
	/**
	 * Original signature : <code>int vorbis_bitrate_flushpacket(vorbis_dsp_state*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:129</i>
	 */
	int vorbis_bitrate_flushpacket(vorbis_dsp_state vd, ogg_packet op);
	/**
	 * Vorbis PRIMITIVES: synthesis layer ******************************<br>
	 * Original signature : <code>int vorbis_synthesis_idheader(ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:134</i>
	 */
	int vorbis_synthesis_idheader(ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_synthesis_headerin(vorbis_info*, vorbis_comment*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:136</i>
	 */
	int vorbis_synthesis_headerin(vorbis_info vi, vorbis_comment vc, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_synthesis_init(vorbis_dsp_state*, vorbis_info*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:138</i>
	 */
	int vorbis_synthesis_init(vorbis_dsp_state v, vorbis_info vi);
	/**
	 * Original signature : <code>int vorbis_synthesis_restart(vorbis_dsp_state*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:140</i>
	 */
	int vorbis_synthesis_restart(vorbis_dsp_state v);
	/**
	 * Original signature : <code>int vorbis_synthesis(vorbis_block*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:142</i>
	 */
	int vorbis_synthesis(vorbis_block vb, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_synthesis_trackonly(vorbis_block*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:144</i>
	 */
	int vorbis_synthesis_trackonly(vorbis_block vb, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_synthesis_blockin(vorbis_dsp_state*, vorbis_block*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:146</i>
	 */
	int vorbis_synthesis_blockin(vorbis_dsp_state v, vorbis_block vb);
	/**
	 * Original signature : <code>int vorbis_synthesis_pcmout(vorbis_dsp_state*, float***)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:148</i>
	 */
	int vorbis_synthesis_pcmout(vorbis_dsp_state v, PointerByReference pcm);
	/**
	 * Original signature : <code>int vorbis_synthesis_lapout(vorbis_dsp_state*, float***)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:150</i>
	 */
	int vorbis_synthesis_lapout(vorbis_dsp_state v, PointerByReference pcm);
	/**
	 * Original signature : <code>int vorbis_synthesis_read(vorbis_dsp_state*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:152</i>
	 */
	int vorbis_synthesis_read(vorbis_dsp_state v, int samples);
	/**
	 * Original signature : <code>long vorbis_packet_blocksize(vorbis_info*, ogg_packet*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:154</i>
	 */
	NativeLong vorbis_packet_blocksize(vorbis_info vi, ogg_packet op);
	/**
	 * Original signature : <code>int vorbis_synthesis_halfrate(vorbis_info*, int)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:156</i>
	 */
	int vorbis_synthesis_halfrate(vorbis_info v, int flag);
	/**
	 * Original signature : <code>int vorbis_synthesis_halfrate_p(vorbis_info*)</code><br>
	 * <i>native declaration : /home/yonran/Downloads/libvorbis-1.3.3/include/vorbis/codec.h:158</i>
	 */
	int vorbis_synthesis_halfrate_p(vorbis_info v);
}
